# default config at https://github.com/rubocop-hq/rubocop/blob/master/config/default.yml

AllCops:
  Include:
    - '**/*.gemspec'
    - '**/*.rake'
    - '**/*.rb'
    - '**/Gemfile'
    - '**/Rakefile'
  Exclude:
    - 'spec/**/*'
    - 'db/**/*'
    - 'config/**/*'
    - 'bin/**/*'
  TargetRubyVersion: 2.6.6

# Commonly used screens these days easily fit more than 80 characters.
Layout/LineLength:
  Max: 120

# Too short methods lead to extraction of single-use methods, which can make
# the code easier to read (by naming things), but can also clutter the class
Metrics/MethodLength:
  Max: 20

# The guiding principle of classes is SRP, SRP can't be accurately measured by LoC
Metrics/ClassLength:
  Max: 1500

Style/Documentation:
  Enabled: false

# Single quotes being faster is hardly measurable and only affects parse time.
# Enforcing double quotes reduces the times where you need to change them
# when introducing an interpolation. Use single quotes only if their semantics
# are needed.
Style/StringLiterals:
  EnforcedStyle: double_quotes

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*.rb'
    - 'lib/**/*.rake'

# These lines are to supress unconfigured warnings for new cops.
# In the future the solution outlined on this page should be used: https://docs.rubocop.org/en/latest/versioning/
# However, this is parameter not yet supported -- see https://stackoverflow.com/questions/61108623/vscode-rubocop-complaining-about-unconfigured-cops
# We should also consider whether we actually want to enable any of these.
Lint/RaiseException:
  Enabled: false
Lint/StructNewOverride:
  Enabled: false
Style/HashEachMethods:
  Enabled: false
Style/HashTransformKeys:
  Enabled: false
Style/HashTransformValues:
  Enabled: false
Layout/EmptyLinesAroundAttributeAccessor:
  Enabled: false
Layout/SpaceAroundMethodCallOperator:
  Enabled: false
Style/ExponentialNotation:
  Enabled: false
Style/SlicingWithRange:
  Enabled: false
