language: ruby
rvm:
  - 2.6.6
before_install:
  - gem install bundler:2.1.4
install:
  - bundle install
before_script:
  - cp config/database.yml.travis config/database.yml
script:
  - rails db:create
  - rails db:migrate
  - rails db:seed
  - rails check:no_fix
addons:
  chrome: stable
  postgresql: "9.4"
dist: trusty
